version: "3.7"
services:
    owncloud:
        image: owncloud/server:10.6.0

        restart: always

        ports:
            - 8080

        healthcheck:
            test: ["CMD", "/usr/bin/healthcheck"]
            interval: 10s
            timeout: 5s
            retries: 5

        depends_on:
            mariadb:
                condition: service_healthy
            redis:
                condition: service_healthy

        networks:
            - default

        environment:
            OWNCLOUD_DB_TYPE: mysql
            OWNCLOUD_DB_HOST: mariadb
            OWNCLOUD_REDIS_ENABLED: 1
            OWNCLOUD_REDIS_HOST: redis

        volumes:
            - owncloudData:/mnt/data

    mariadb:
        image: mariadb:10.5.8

        command: --character-set-server=utf8 --collation-server=utf8_general_ci

        restart: always

        healthcheck:
            interval: 10s
            timeout: 5s
            retries: 5

        networks:
            - default

        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: 1

        volumes:
            - ./databaseEntrypoint:/docker-entrypoint-initdb.d
            - owncloudMariadbData:/var/lib/mysql

    redis:
        image: redis:6.0.9-alpine

        restart: always

        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 10s
            timeout: 5s
            retries: 5

        networks:
            - default

        volumes:
            - owncloudRedisData:/data

volumes:
    owncloudData:
        driver: local
    owncloudMariadbData:
        driver: local
    owncloudRedisData:
        driver: local
